services:
  smart-guard-listener:
    build: .
    environment:
      MQTT_BROKER: ${MQTT_BROKER:-broker.emqx.io}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_USERNAME: ${MQTT_USERNAME:-}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-}
      MQTT_TOPICS: ${MQTT_TOPICS:-dJfmRURS5LaJtZ1NZAHX86A9uAk4LZ-smart-guard-rfid-response}
      API_BASE_URL: ${API_BASE_URL:-http://172.17.38.182:8021/api}
      API_TOKEN: ${API_TOKEN:-58|FQntWTcX1ZSdKAp8ItJAhNBl9OBmYq2HYE6quIP605d554ef}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    restart: unless-stopped
